### PR TITLE
Add warning message for virtual media page

### PR DESCRIPTION
**Pull request by BenPai99**
Remind users not to reload the browser or close the page during
operation.

Signed-off-by: Ben Pai <Ben_Pai@wistron.com>

### CODE REVIEW

**Comment by Erich-Hauptli** [comment]
This addresses SW522143 on Mowgli.

**Comment by gtmills** [comment]
@Erich-Hauptli https://w3.rchland.ibm.com/projects/bestquest/?defect=SW522143 is describing a timeout. 
"I see the virtual media timing out in line with the time line Mark gave"
I don't see how this fixes? 

Can you add a better description of why this is needed? 
Can you add a screenshot of what this looks like?

**Comment by Erich-Hauptli** [comment]
@gtmills The timeout occurs only when the page is refreshed or closed.  This does not fix the issue, it is just a warning to customers to hopefully avoid the issue.

**Comment by gtmills** [comment]
@Erich-Hauptli Can we upstream this? 
This seems fine to me, although I fail to see how this will make much of a difference

**Review by gtmills — APPROVED** [review]

**Pull request merged**
